image: steigr/zfs:onbuild

stages:
- build
- release
- update

variables:
  GITHUB_USER: steigr
  GITHUB_REPO: coreos-zfs
  DEST: /artifacts/build
  COREOS_RELEASE: "695.2.0"
  COREOS_CHANNEL: "beta"
  GITHUB_RELEASE_URL: "https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2"
  ZFS_VERSION: "0.6.5.8"

build:
  only:
  - tags
  - develop
  stage: build
  artifacts:
    untracked: true
  variables:
    INSTALL_MOD_PATH: /usr/share/oem/zfs
    OEM_PATH: /usr/share/oem/zfs
    BIN_DIR: /usr/share/oem/zfs/bin
    LIB_DIR: /usr/share/oem/zfs/lib64
    SBIN_DIR: /usr/share/oem/zfs/sbin
    SYSTEMD_DIR: /etc/systemd
    UDEV_DIR: /etc/udev
    MODULES_LOAD_DIR: /etc/modules-load.d
    DEFAULT_FILE: /etc/default/zfs
    SYSTCONF_DIR: /etc/zfs
  script:
  - ./build.sh

release:
  stage: release
  only:
  - tags
  script:
  - ./upload.sh

update:
  stage: update
  only:
  - update
  script:
  - ./mk-branch.sh
